#pragma once
namespace FH
{
	enum class GameEvent
	{
		EVENT_PLAYER_MOVED_LEFT,
		EVENT_PLAYER_MOVED_RIGHT,
		EVENT_PLAYER_MOVED_UP,
		EVENT_PLAYER_MOVED_DOWN,
		EVENT_PLAYER_DIED,
		EVENT_PLAYER_GAINED_POINTS,

		EVENT_BAG_WIGGLE,
		EVENT_BAG_FALL,
		EVENT_BAG_BREAK,
		EVENT_BAG_PICKUP
	};
}